### ISSUE TITLE
Non-GL hexen 2

### ISSUE THREAD

**Issue by Exarkuniv** [Exarkuniv/RetroPie-Extra#105]
tried it, plays like shit, very choppy, and cant get fullscreen
not going to include it

**Comment by symbios24** [comment]
It plays fine to me with a combination of xinit and matchbox

**Comment by Exarkuniv** [comment]
not on when i just tryied it,

**Comment by symbios24** [comment]
How you run it exactly ? 

It uses the quake engine so it runs the same way as quake

**Comment by Exarkuniv** [comment]
the problem was my image, it was a bad image, everything was messed up. 

i still think GL version is better, but it plays good enough. script is made
