### ISSUE TITLE
alternate lr-easyrpg script

### ISSUE THREAD

**Issue by fry-guy** [Exarkuniv/RetroPie-Extra#118]
You list lr-easyrpg under "Removed or broken scripts" due  to installation failure. I wonder if you might want to check out [this script](https://github.com/mictjs/RetroPie-Extra-WIP/blob/master/scriptmodules/libretrocores/lr-easyrpg.sh)? I was [able use it  to install lr-easyrpg without issue](https://www.reddit.com/r/RetroPie/comments/en3kpd/comment/i1770mp/?utm_source=reddit&utm_medium=web2x&context=3) earlier this year on my RPI4 Retropie setup.

**Comment by Exarkuniv** [comment]
i will take a look, thanks

**Comment by Exarkuniv** [comment]
stills fails, 
it ends up being the same script.
i go back to this another day once i get new scripts made

**Comment by fry-guy** [comment]
Strange, I wonder what's different on my system? Thanks for checking it.

**Comment by Exarkuniv** [comment]
it depends on when you ran it, if it was at the start of the year or longer, a lot could of changed on both RetroPie or libretro ends

thats the fun part with scripts, depends on how they are written they can stop working at any point.
