### ISSUE TITLE
SW expansion not working

### ISSUE THREAD

**Issue by Exarkuniv** [Exarkuniv/RetroPie-Extra#121]
twin dragon expansion will not start, 

had to go back to a older commit to just get the right verion of the game to start, maybe need to go back more to get  twin dragon expansion to work also.

**Comment by symbios24** [comment]
Hi i tried every possible way to run twin dragon its not working,wanton expansion is working though

**Comment by Exarkuniv** [comment]
this as been verified to be working, and there was a fix by the dev to clear up the first issue so the script was changed back.

the dragon zip should only have the files int it. if there is a folder within the zip, that is holding the files that is the problem.
once i pulled the files out of the folder and only have the required files in the .zip Twin Dragon started just fine

**Comment by Exarkuniv** [comment]
so the wrong way,(the way i had before) was
dragon.zip
  |
  dragon(a folder)
     |
     all the *.MAP, *.VOC, *.ART and *.ANM files from "Classic Complete" version (free download from GOG)

this way will not work, all the *.MAP, *.VOC, *.ART and *.ANM files cant be in a folder

they need to be this

dragon.zip
   |
  all the *.MAP, *.VOC, *.ART and *.ANM files from "Classic Complete" version (free download from GOG)

theres going to be about 73 files in the dragon.zip (or there is for mine

hope this helps. so you know there is no title change, the only way you know it will work is if you go to play the registered version of the game( i know weird there is no title letting you know what you are playing)

if its still not working for you, i dont know, it is working for me and s1eve-mcdichae1 since he is the one who cleaned up the script, i had him check to make sure it works.

**Comment by symbios24** [comment]
So i put in a folder: the sw executable the dragon.zip the tdragon.grp the sw.grp and all the MAP, *.VOC, *.ART and *.ANM files from the shadow warrior retail game and i run the game with ./sw -tdragon.grp ??

Thanks

**Comment by Exarkuniv** [comment]
this is what i have in my folder using the script that we have made
dragon.zip 
sw.grp
sw.rts
wanton.dat
wt.grp
a folder named music with all the .ogg files in it

if you are doing this your own way, yes you need the sw executable
and you use ``sw -gdragon.zi`` and select the registered-version episode

you dont need tdragon.grp

**Comment by symbios24** [comment]
Just an info the ogg files working only inside the folder that has the sw executable and not if they are in a folder with the name :music

Wanton works if you have only the wt.grp and the sw exe only in the same folder and not another file/s  otherwise it loads the normal game 

Twin dragon did not work no mater what i did its like the "-" switch is not acceptable

All the files are taken from the gog release of the game.

**Comment by Exarkuniv** [comment]
then something is messed up with your build, i have loaded a clean OS and used the install script, and the games start just fine for me,

yes the music does not work sitting in the music folder, once out it works fine

sorry i cant be anymore help with this for you as its working as it should for me, 
thanks for the fix for the music though

**Comment by symbios24** [comment]
No problem apparently my dragon.zip file is not correct i get a" bus error " on running
It has 73 files inside including the loader.iaf file otherwise they 72.

**Comment by Exarkuniv** [comment]
i have added my dragon.zip to my ``game data`` repo. 

you might have to download the whole repo, but its there.

**Comment by symbios24** [comment]
Thanks
