### ISSUE TITLE
openrct2 - missing package on debian 11

### ISSUE THREAD

**Issue by tacgnol3** [Exarkuniv/RetroPie-Extra#152]
On debian 11, these packages are missing :

libjansson-dev libspeex-dev libspeexdsp-dev libcrypto++-dev libbenchmark-dev libbenchmark-ocaml-dev duktape-dev libduktape203 libflac++-dev ccache

**Comment by Exarkuniv** [comment]
all my ports are build and tested on the current build of RetroPie. which is only debian 10. 
Until they are a running version on debian 11. im not going to be much help. 

but feel free to change what you need to, to get it working for you

**Comment by tacgnol3** [comment]
I enabled debian testing just for the install, changed libduktape203 for libduktape207, and it went fine after that. then disabled the testing branch.

**Comment by Exarkuniv** [comment]
ok, ill close this, 

once a official image is out, i will go back and make it work on both
