### ISSUE TITLE
Remove lr-beetle-pce.sh

### ISSUE THREAD

**Issue by Gemba** [Exarkuniv/RetroPie-Extra#160]
Remove the scriptmodule from this repo as it has been integrated into RetroPie-Setup.
And add it to the Hall of fame in the README.md :)

https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-beetle-pce.sh

**Comment by Exarkuniv** [comment]
Remove it sure, add it nope 
this was added by someone else not me, or from Extras
