### ISSUE TITLE
Devilutionx error

### ISSUE THREAD

**Issue by actraiser30** [Exarkuniv/RetroPie-Extra#164]
Hello there just for your info devilutionx installation in not working,after a while it stops with an error saying: 

home/pi/RetroPie-Setup/ext/RetroPie-Extra/scriptmodules/ports/devilutionx.sh line 31: cmake: command not found
home/pi/RetroPie-Setup/ext/RetroPie-Extra/scriptmodules/ports/devilutionx.sh line 32: cmake: command not found
Could not successfully build devilutionx diablo engine
(/home/pi/RetroPie-Setup/tmp/build/devilutionx/build/devilutionx not found)

**Comment by Exarkuniv** [comment]
What you posted doesn't tell me anything. That's the generic error that everything says when it fails

You need to post the log file.

**Comment by actraiser30** [comment]
cmake is missing from the depends you can understand that i think,when I
installed it manual everything worked fine.
