### ISSUE TITLE
Manaplus works

### ISSUE THREAD

**Issue by actraiser30** [Exarkuniv/RetroPie-Extra#167]
Hi there
Manaplus works great can you put it back to extras?

Thanks

**Comment by actraiser30** [comment]
Any change that you will put this script back ?? It's over 3 months since I ask you.

**Comment by actraiser30** [comment]
Don't bother probably too much for u

**Comment by Exarkuniv** [comment]
i have other stuff im doing. if you are in a rush for you. you can open a PR for it

**Comment by actraiser30** [comment]
No problem just do your things.

**Comment by actraiser30** [comment]
Thx just to let you know the wine installation does not finish successful it stucks in the phase you see in the photo cannot find a solution yet

![305634823-ade4b217-77e0-4d4a-9d95-0bfa1b00b784](https://github.com/Exarkuniv/RetroPie-Extra/assets/38106933/c45f1258-a1b9-48e5-887e-ffad66a1b296)

Thanks
