### ISSUE TITLE
Freeciv cannot compile

### ISSUE THREAD

**Issue by actraiser30** [Exarkuniv/RetroPie-Extra#169]
Hello, merry Christmas

Freeciv is missing a package/depend that without it cannot be compiled

libcurl4-openssl-dev

Thanks

**Comment by Exarkuniv** [comment]
no clue what you are talking about, installed just fine for me with a clean image
installed freeciv-2.6.6 no issues

libcurl4-openssl-dev is installed by default from RetroPie. so its you build.
so no not going to add it

**Comment by actraiser30** [comment]
Whatever,no problem.
