### ISSUE TITLE
Advice on creating a aetherSX2 script

### ISSUE THREAD

**Issue by retropieuser** [Exarkuniv/RetroPie-Extra#177]
I'm writing up some notes on how to get AetherSX2 to install and will add it as a pull request when I think it's correct, but I'd like some advice from you @Exarkuniv on writing this please:-

The main issue is that the archive of aetherSX2 that the developer left after quitting the scene is in appimage format, which Raspberry Pi OS doesn't have the dependancies installed for. One of which is fuse, which by installing will stop anyone's desktop folders from working correctly if they have the desktop installed and they'll need to reinstall to get working again. It's outlined here in Ubuntu's case:- https://www.tomshardware.com/how-to/emulate-playstation-2-raspberry-pi

Now I could extract the appimage package and convert it into a .tar.gz like most of the other packages used by RetroPie scripts, but I'm not sure if that'll create some issues in terms of copying the work from the original dev? I took a look around and they appear to have quit the scene entirely so not quite sure how to get their permission to turn this .appimage into a .tz package? 

Or should I just point the script towards https://www.aethersx2.com/archive/desktop/linux/AetherSX2-v1.5-3606.AppImage and add fuse libappimage-dev as the dependants? With the knowledge it might knock over some people's desktop installs?

**Comment by Exarkuniv** [comment]
hmm

1. you making the file as a .tz should not be a issue. you are not really changing anything since the appimage is just a compressing tool. (this is what i would do. i do remember reading all about the thing with the dev)
2. 
is fuse needed for aetherSX2 to work? or is it just for the appimage to open?

**Comment by retropieuser** [comment]
Yeah that's what I figured but I didn't feel comfortable compressing and uncompressing the devs work, although I should appimage is just a Linux compression tool? Like changing it from .zip to .rar in windows or Mac?

fuse is a dependency to load appimage files, I need to test from a fresh 64bit install as I don't feel comfortable purging fuse off my machine in case it wrecks all my current setup I play on

But when you extract the appimage, there's an app, some resources like GUI pngs and an SDL game controller database, so I think it should run without fuse once turned into a .tz

**Comment by Exarkuniv** [comment]
> Yeah that's what I figured but I didn't feel comfortable compressing and uncompressing the devs work, although I should think of appimage as just a Linux compression tool? Like changing it from .zip to .rar in windows or Mac?

as far as i can tell yes thats exactly what a appimage is
 
> fuse is a dependency to load appimage files, I need to test from a fresh 64bit install as I don't feel comfortable purging fuse off my machine in case it wrecks all my current setup I play on

trust me i get that. i have like 3 sd cards that i swap around when i do scripts. Never use your main one. i learned the hard way on that


> But when you extract the appimage, there's an app, some resources like GUI pngs and an SDL game controller database, so I think it should run without fuse once turned into a .tz

that sound about right with the very few appimages i have used in the past

**Comment by retropieuser** [comment]
Script made and added. Thanks!
