### ISSUE TITLE
Wine issue?

### ISSUE THREAD

**Issue by Exarkuniv** [Exarkuniv/RetroPie-Extra#180]
test the stand alone script

**Comment by actraiser30** [comment]
Hi here is what I tested

Wine works in buster but only if you do a full-upgrade and upgrades the kernel components also,in bullseye and bookworm does not work.

**Comment by Exarkuniv** [comment]
> Wine works in buster
thanks for verifying that it still works, might look into getting using a newer version of it though

> bullseye and bookworm does not work
yes those will not as the script is installing the only the buster version

**Comment by actraiser30** [comment]
I haven't think that to change the buster to bookworm from the script.

**Comment by actraiser30** [comment]
I changed all the lines from buster to bookworm but it did not work failed to install :/

Also tried this script

**Comment by Exarkuniv** [comment]
good try
illl get to it once i get more of my testing done. 
it just might not be something that will work on new OSs.

**Comment by actraiser30** [comment]
It's ok if it won't work in bookworm,PI4 is still good, at least to work in older OS and have mesa and wine updated to more recent versions

Thanks

**Comment by Exarkuniv** [comment]
again, thanks for testing this out. 
i cant really remember why i opened a issue. and at this point i dont think it matters much

**Comment by actraiser30** [comment]
No it doesn't matter but its good if it's possible to be updated or not nevertheless 

Thanks

**Comment by Exarkuniv** [comment]
> 7.0.0 and worked

cool, ill update it to that then

**Comment by actraiser30** [comment]
I'm trying to install wine in bullseye in pi4

Mesa and box install fine in wine it stucks in configuring wine I run the wine installer manual with: sudo ./retropie_packages.sh wine 
To see what happens after,as you can see in the photo after "configuring wine" somehow it runs wine so the installer cannot continue.
Is it possible to check the script and disable the running of wine?

![IMG_20241118_143631_232_LL](https://github.com/user-attachments/assets/f6a7fa44-5731-4047-8f0c-bc572e7b54ac)

Highest wine that can be installed in bullseye is 9.0

**Comment by Exarkuniv** [comment]
Until there is a official image for the Pi4 im not changing it to 9.0

since i dont have bullseye on my pi4 and im not going to mess with that im only testing with the offical image. and it works as it should.

the only thing in the config part of the script is making mulation Station scripts for Wine. there is nothing that "runs" 
you can delete the everything that is in the "cat" part, but no .sh files will be made then

**Comment by actraiser30** [comment]
Thanks,I haven't say to change anything,just a little help to make it work, unfortunately it did not work,probably an incompatibility issue with bullseye.thanks for the help.
