### ISSUE TITLE
AetherSX2 in Pi 5

### ISSUE THREAD

**Issue by Dastronik** [Exarkuniv/RetroPie-Extra#184]
I have tested it and i got a Blackscreen and the Game won´t start . I switched to the kernel8.img , i have the right BIOS , i tested it with multiple Games ( GTA 3 included ) and i used the latest script . I´m on Raspberry Pi 5 . When you can tell me how i open the Runcommand window in Retropie to see what´s going on , then i can provide further Information .

**Comment by darksaviorx** [comment]
I can't get it to load any games. Pi5 as well. I'm using the kernel8.img. I believe I have the right bios..
https://pastebin.com/X3fx43N6

**Comment by Dastronik** [comment]
I just installed Raspberry Pi OS 64 Bit and Retropie again . The only thing that i put on my SSD was the Emulator ( AetherSX2 ) , the BIOS and 2 Games . And Nothing has changed . Just to clarify my BIOS File is ps2-0230e-20080220.bin

**Comment by Exarkuniv** [comment]
not sure whats going on with your builds. i have to redo my system 5 time while testing to find the missing files for sound to work and it has always started for me. the only time it doesn't is when i forgot to add the ``kernel8.img`` to the ``boot/firmware/config.txt`` file

are you using the Pi OS 64bit lite? im using the March 15th 2024 build
and the sets to build RetroPie follow this https://github.com/danielfreer/raspberrypi5-retropie-setup

exit emulation station
```
 cd /opt/retropie/emulators/aethersx2/AetherSX2-v1.5-3606/usr/bin 

sudo xinit ./aethersx2
```

this will bring up the GUI from there you can move around the menu
doing it this way does not load the .ini file so it will not have the link to the bios files FYI

my bios are ``ps2-0220a-20060905.bin`` and ``scph39001.bin``

**Comment by Dastronik** [comment]
Are you mean , by add the kernel8.img to the config.txt this 

# Run in 64-bit mode
arm_64bit=1

when not , i have not done that . What else i have to do with it open the kernel8.img with the texteditor and copy that ?
And then paste it into the config.txt . And where do i have to put it in ? Sorry i´m a Noob

**Comment by Exarkuniv** [comment]
in the command line run this
``sudo nano /boot/firmware/config.txt``
then at the end of everything 
add this
``kernel=kernel8.img``

then
 press ctrl+O AND ctrl+X to exit from terminal window
this will save it

if you are running the PiOS lite or the one with a desktop

**Comment by Dastronik** [comment]
Thank you , I understand . I´m currently on the one with the desktop .

**Comment by Dastronik** [comment]
Do i break something if i try if it works ?

**Comment by Exarkuniv** [comment]
no you are not going to break anything,
but it might not work 100%, but it might. i dont know

i make all the scripts to be ran on a OS without desktop as that is how retropie runs their images
and i will not be able to help as much since my OS does not have a desktop either

**Comment by Dastronik** [comment]
When this is not working , i´m switching to the lite OS . But today i´m not willing to sit another 4 hours behind the screen and wait for Retropie to finish .

**Comment by Exarkuniv** [comment]
trust me, know how you feel. i has to make my own image on a 8gig card so i didn't have to keep rebuilding retropie  each time i broke it from my testing and building

**Comment by Dastronik** [comment]
When you mean behind everything , did you really mean behind every line of text or just the ones in white ? Because i put it behind every line of text and now the Raspi 5 won´t even boot . Nice

**Comment by Exarkuniv** [comment]
no, sorry
it would be the very last line in that file. 

```
[all]
kernel=kernel8.img
```

you might be able to pull the sd card out of the pi, put it in a computer and in the ``bootfs`` drive that you can open. there is a config.txt

you might be able to then remove all the lines you did and then add the above line to the end of the text
put it in your pi and hopefully it will work again

**Comment by Dastronik** [comment]
It´s not a big of a deal . I will try it , if that is not working then i wait until tommorow and install the lite OS .

**Comment by Dastronik** [comment]
It worked , it booted up again plus the Emu starts now . Now i´m going to try diffrent BIOS because the one i used is not working . 
Thank you for your help and your patience . I will try the ones you use next and then we will see .

**Comment by Exarkuniv** [comment]
it will be easyer just to use the RetroPie-extras install way to do it. that way it is put in the correct place and you dont have any error from moving it from a PC to the Pi

its in the readme. on how to do it
aethersx2 is in the emulators section

**Comment by Dastronik** [comment]
Thank you

**Comment by Dastronik** [comment]
You are using just these 2 BIOS Files right ? No other files like the EROM or others .

**Comment by Exarkuniv** [comment]
i do have a few others in there. 
the system has AUTO on by default. so it will use what is best for the game. (or thats what i think it will do)

**Comment by Dastronik** [comment]
Can you tell what others ? Just in case

**Comment by Exarkuniv** [comment]
ps2-0220a-20060905.bin
ps2-0220e-20050620.bin
rom1.bin
scph10000.bin
SCPH-10000_BIOS_V1_JAP_100.BIN
scph39001.bin
SCPH-70004_BIOS_V12_PAL_200.BIN
SCPH-70004_BIOS_V12_PAL_200.EROM

**Comment by Exarkuniv** [comment]
glad to hear
