### ISSUE TITLE
Experimental AetherSX2 script compatible with Pi 4?

### ISSUE THREAD

**Issue by ImAQwertyGuy** [Exarkuniv/RetroPie-Extra#191]
Hi,
I wanted to give PS2 games a shot on my Pi 4. I guess I'll see whether I'm happy with the performance or not.
However when I tried to install AetherSX2 it said Pi 4s weren't supported.
I went into the script on my end to remove !rpi4. It installed just fine.
However it would be nice if you had an AetherSX2 script that was marked as experimental that could install on a Pi 4?

**Comment by Exarkuniv** [comment]
I have it for the pi5 mainly because the five is more powerful and the PS2 emulator needs more power than what the pi4 has

But I might change it to only be for 64bit maybe

So test some games and see how well it works

For now it stays as is

**Comment by Exarkuniv** [comment]
changed it so it can install on pi4( i dont think it will run that well to make games playable)  but its not my build

**Comment by ImAQwertyGuy** [comment]
The only game I've test played so far was Sonic Heroes. I'm really impressed with the performance.
The story select screen was laggy but other than that the game ran really well.
Maybe I'll try some more PS2 games later, mainly Sonic ones.
