### ISSUE TITLE
Supermodel3

### ISSUE THREAD

**Issue by Giandj** [Exarkuniv/RetroPie-Extra#197]
Hi thanks for your works,
 I can confirm that AetherSX2 for Retropie 4.8.8 and pi5 (with kernel8.img in /boot/firmware/config.txt) works very well, all PS2 games at 60FPS !!! (using "minimum" instead of "basic" blending in graphics setup, this is very important to share to friends) with Retropie-Extra.
Also lr-cannonball is great.
(All joystick+buttons are mapped fine by libretro).

Instead on Sega Supermodel3 all games works fine (if you set -res=1024x768 and disable the -fullscreen, parameters, and enable -stretch for 16:9 monitors/TV )
But I cannot Exit from Supermodel3 without a keyboard...
Do you Have an Idea , how to bind an SDL button instead of ESC , to exit and quit emulator ?

I have searched everywhere but noone has found a method to use a button to quit supermodel3,  without pressing the ESC key on keyboard.
(On my arcade cabinet I don"t want to use a keyboard, if possible).
Thank for your work.

**Comment by Exarkuniv** [comment]
Unfortunately no
i also have come across this problem, and i have not looked more into it. 

but a new Script as been added to the main RetroPie setup for Sega Supermodel3, 

https://retropie.org.uk/docs/Supermodel/
it does not have anything listed for exit in the doc, but you might be able to edit the file that is listed in the DOC and map a key to it. 

that file might even work for the scripts in my Repo

**Comment by Exarkuniv** [comment]
Not really a issue with the script or anything I can control.
