### ISSUE TITLE
GMLoader can't load Maldita Castilla

### ISSUE THREAD

**Issue by Larkas** [Exarkuniv/RetroPie-Extra#200]
I just installed gmloader, but the system fails to launch Maldita Castilla. Spelunky works just fine, as does [AM2R](https://www.reddit.com/r/AM2R/comments/1f16833/am2r_raspberry_pi_take_5/). I'm using a weekly build of RetroPie bullseye 4.8.8 @ RPi4.

**Comment by Exarkuniv** [comment]
Well looking at the link it looks like they took it down. So it doesn't work cuz it didn't download it.  

I'll have to test it to make sure

**Comment by Exarkuniv** [comment]
yes it was a dead link, fixed now
