### ISSUE TITLE
aethersx2.sh assumes Retropie user is 'pi'

### ISSUE THREAD

**Issue by gilesco** [Exarkuniv/RetroPie-Extra#202]
aethersx2.sh assumes Retropie user is 'pi', but that is often not the case with recent builds through Raspberry Pi Imager.

This causes aethersx2 to not find the Retropie BIOS/ps2 folder

I was able to manually set the absolute path in ~/.config/aethersx2/inis/PCSX2.ini to my BIOS folder, and it worked from that point on.

Might also be good to add a note that /boot/firmware/config.txt needs to have kernel=kernel8.img to run the AetherSX binary, otherwise it segfaults.

**Comment by gilesco** [comment]
It was easy to self fix for myself. The standard retropie downloads use the 'pi' user by the looks of it, so many users won't encounter the problem. Adding a bit of easy to find documentation might be just about enough :-)

**Comment by Exarkuniv** [comment]
Yes the standard build of RetroPie uses pi as the username 
That is the reason why initially it was used

**Comment by Exarkuniv** [comment]
done
