### ISSUE TITLE
lr-melonds installation

### ISSUE THREAD

**Issue by Revolverdev** [Exarkuniv/RetroPie-Extra#225]
I wanted to download a DS emulator for my rpi5, and heard lr-melonds was the best performing in general, so I got the core's installation script, and went to set it up, and it says in the flags:

all rpi5! rpi4

I have a 64bit, 8gb ram pi5 setup.

I also had an issue with SRB2kart and openlara

**Comment by Exarkuniv** [comment]
Well openlara doesn't work on 64bit. So that's why it doesn't work 
Same for lr-melonds. It works on the pi4
Use lr-melondsds. That works on pi5

I also know about SRB2kart. Have not figured out that one yet. But that also might be for now. Not playable on the 5 since it's 64bit
