### ISSUE TITLE
RetroPie-Setup is too old

### ISSUE THREAD

**Issue by RSlegers** [Exarkuniv/RetroPie-Extra#226]
When i want to install RetroPie-Extras i get a error, that mine RetroPie-Setup is too old .

But even when i do git pull master origin on RetroPie-Setup, the error stays.

Is there a solution ?

**Comment by Exarkuniv** [comment]
yes update it this way,
https://retropie.org.uk/docs/Updating-RetroPie/
not from the github directly

i just did that on my pi4 and i can use the RetroPie-Extras installer correctly

i will double check my pi5 again, but that will take a little longer

**Comment by Exarkuniv** [comment]
I tested this on my pi5. im going to be changing the wording a little to say for the update to be done through the main setup menu

**Comment by KTac** [comment]
I am having the same issue, and I have updated via the RetroPie setup menu. I am still getting the error that my RetroPie-Setup directory is too old.

**Comment by Exarkuniv** [comment]
@KTac does it say version 4.8.9 in the setup menu?

**Comment by KTac** [comment]
Yes it does

![image](https://github.com/user-attachments/assets/f7ea47c4-d438-4b6a-813a-a3f3d76d6a9c)

**Comment by RSlegers** [comment]
Also here updating won't work.

RetroPie is updated, also RetroPie-Extra is updated.

Op di 29 okt 2024 05:18 schreef KTac ***@***.***>:

**Comment by actraiser30** [comment]
Strange problem it was working before even if the retropie-setup was from years back

**Comment by RSlegers** [comment]
I installed Raspberry Pi os and installed RetroPie with the installer script (there is no rpi5 image of RetroPie yet)

Don't know if this causes the problems?

**Comment by Exarkuniv** [comment]
we are changing how some of the helper scripts are being handled, to keep it in line with what Retropie is doing, 
if the install is too old then the scripts will not work. 

which is why there is now a check on what version you are running. 
it worked on all my tests that i did. which is why i accpted the pull

**Comment by Exarkuniv** [comment]
did clean install, yet again. i saw that the warning came up before i updated RP, and after i was able to get in and install scripts. 

so yes it does work, not sure why all of you are getting the warning, im not doing anything different. so i will delete the warning for now till i find a better way

real head scratcher
