### ISSUE TITLE
gmloader fails to build

### ISSUE THREAD

**Issue by KTac** [Exarkuniv/RetroPie-Extra#228]
Running on a Pi 5 following official directions for manual build. Trying to install gmloader from source fails. Below is a snip from the log at the point where it fails. The full log is attached.

`[ 96%] Building C object CMakeFiles/gmloader.dir/platform/linux/so_util_linux.c.o
/usr/bin/cc  -I/usr/include/freetype2 -I/usr/include/SDL2 -I/home/pi/RetroPie-Setup/tmp/build/gmloader/platform/linux -I/home/pi/RetroPie-Setup/tmp/build/gmloader/platform/common -I/home/pi/RetroPie-Setup/tmp/build/gmloader/bridges -I/home/pi/RetroPie-Setup/tmp/build/gmloader/jni -I/usr/lib/gcc-cross/arm-linux-gnueabihf/12/include -L/usr/lib/gcc-cross/arm-linux-gnueabihf/12 -I/usr/lib/gcc-cross/arm-linux-gnueabihf/12/include -L/usr/lib/gcc-cross/arm-linux-gnueabihf/12 -D_GNU_SOURCE=1 -Wfloat-conversion -Os -mthumb -mcpu=cortex-a9 -mfpu=vfpv3-d16 -mthumb -mcpu=cortex-a9 -mfpu=vfpv3-d16 -fmacro-prefix-map="/home/pi/RetroPie-Setup/tmp/build/gmloader"/=/ -fmacro-prefix-map="/home/pi/RetroPie-Setup/tmp/build/gmloader"/=/ -O3 -DNDEBUG -MD -MT CMakeFiles/gmloader.dir/platform/linux/so_util_linux.c.o -MF CMakeFiles/gmloader.dir/platform/linux/so_util_linux.c.o.d -o CMakeFiles/gmloader.dir/platform/linux/so_util_linux.c.o -c /home/pi/RetroPie-Setup/tmp/build/gmloader/platform/linux/so_util_linux.c
/home/pi/RetroPie-Setup/tmp/build/gmloader/platform/linux/so_util_linux.c: In function ‘block_valid’:
/home/pi/RetroPie-Setup/tmp/build/gmloader/platform/linux/so_util_linux.c:31:16: warning: comparison between pointer and integer
   31 |   return block != MAP_FAILED;
      |                ^~
make[2]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/gmloader/build'
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/gmloader.dir/all] Error 2
make[1]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/gmloader/build'
make: *** [Makefile:91: all] Error 2
Could not successfully build gmloader - GMLoader - play GameMaker Studio games for Android on non-Android operating systems (/home/pi/RetroPie-Setup/tmp/build/gmloader/build/gmloader not found).
/home/pi/RetroPie-Setup`
[rps_2024-10-29_135351.log.gz](https://github.com/user-attachments/files/17561207/rps_2024-10-29_135351.log.gz)

**Comment by Exarkuniv** [comment]
Something must of changed upstream. I'll take a look into this. Thanks

**Comment by Exarkuniv** [comment]
@gemba

**Comment by Gemba** [comment]
Yes, upstream is using 2.30.8. Change [this line](https://github.com/Exarkuniv/RetroPie-Extra/blob/878e21ec73bc398adda4f2d4a9b75f709d807897/scriptmodules/ports/gmloader.sh#L128) to the upstream version and let it run again.

I had no luck with calling `get_pkg_ver_sdl2` of `sdl2.sg` module, that's why I put it hardcoded, it had to break sometime... If someone has a clue how to get the version from the sdl2 scriptmodule, that would avoid future breaks.

**Comment by Exarkuniv** [comment]
Cool thanks 
I'll try that tomorrow.

Maybe once there is a official image we can figure out how to hard code it. 
Or trying gmloader next might fix this

**Comment by Exarkuniv** [comment]
@Gemba did you look at how eduke32.sh and ionfury.sh work together? ionfury calls on eduke32 for everything

**Comment by Exarkuniv** [comment]
ok so changing just number does not work,. 
it fails to download that version. so im guessing the file name is different. 
not sure how its not doing it since you copied it from the sdl2.sh

**Comment by Gemba** [comment]
Some additional notes:
- If there is stale a apt hold on `libsdl2-2.0-0:armhf` and `libsdl2-dev:armhf` it should be removed. (`apt-mark showhold` and `sudo apt-mark unhold <pkg>`).
- The new SDL2 version should be installed first (`sudo RetroPie-Setup/retropie_packages.sh sdl2`).
- Afterwards  gmloader should be installable

I will also provide a PR to make the script more robust.
