### ISSUE TITLE
supermodel extentions not present in es_systems.cfg

### ISSUE THREAD

**Issue by ALLRiPPED** [Exarkuniv/RetroPie-Extra#35]
when you install this everything turns out fine accept for the extension for the roms in the es_systems.cfg has a blank space, if I am assuming correctly the platforms.cfg that is in the root RetroPie-Setup folder has to have these extensions and fullname in it or the extensions never get setup.

```
  <system>
    <name>model3</name>
    <fullname>Sega Model 3</fullname>
    <path>/home/pi/RetroPie/roms/model3</path>
    <extension> </extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ model3 %ROM%</command>
    <platform>model3</platform>
    <theme>model3</theme>
  </system>
```

```bash 
model3_exts=".zip"
model3_fullname="Sega Model 3"
```

The lines above if you add them to the platforms.cfg it then shows the .zip in the extension brackets in es_systems.cfg, only problem with that is updating your retropie setup if one chooses to do so would either get hit with "you have modified files please submit your changes", or using --force and overwriting it.

Is there some way to include a custom platforms.cfg while installing it from retropie?

also the same thing happens with lr-vemulator it also is missing the extensions

```bash
vmu_exts=".DCI .dci .VMS .vms .BIN .bin"
vmu_fullname="Visual Memory Unit"
```

**Comment by Exarkuniv** [comment]
i will take a look and see what i can find out how to go about getting that done. 
thanks for finding it 

theres a lot to go through and clean

**Comment by ALLRiPPED** [comment]
@Exarkuniv https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/helpers.sh#L1281

from reading there you can either over write the one in retropie-setup root or place it in the /opt/retropie/configs/all/ folder and I have tested that last one out numerous times and it does work by adding them into the extensions to the es_systems.cfg file.


now if you looks just below the getPlatformConfig here: https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/helpers.sh#L1301

then one need is to format like this
``` addSystem "model3" "System Fullname" ".ext" ```
I just got done testing this last one myself and it solves the problem with the lease amount of resistance.

**Comment by ALLRiPPED** [comment]
https://github.com/Exarkuniv/RetroPie-Extra/pull/36
https://github.com/Exarkuniv/RetroPie-Extra/pull/37

here no use giving you problem without atleast giving up a solution

**Comment by Exarkuniv** [comment]
Thanks for fixing it

I have heard of the helpers.sh. 
Just have not gotten to looking at it. 

I'm still going off every thing that I self taught from a year ago. 
Since I did ask for help back then and never got anything.

I'm slowly getting up to speed

**Comment by Exarkuniv** [comment]
fixed and merged
