### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [Exarkuniv/RetroPie-Extra#67]
A lot of these modules say "this file is part of the RetroPie project" even though that really isn't true. Should we switch over to something that reflects this more accurately? I was thinking something like:

```
# This file is part of RetroPie-Extra, a supplement to The RetroPie Project
#
# RetroPie and RetroPie-Extra are the legal property of their developers, whose
# names are too numerous to list here. For more information, please visit:
#
# https://github.com/RetroPie/RetroPie-Setup
# https://github.com/Exarkuniv/RetroPie-Extra
#
# See the LICENSE.md file distributed with this source and at
# https://raw.githubusercontent.com/Exarkuniv/RetroPie-Extra/master/LICENSE.md
#
```

Alternatively, we could just remove it entirely (some of them don't have it already), or maybe just keep the first line. What do you think?

**Comment by Exarkuniv** [comment]
Ha. I never even payed attention to that. 

I think we can remove that line. 
We only need the important ones.

**Comment by s1eve-mcdichae1** [comment]
> I think we can remove that line. We only need the important ones.

How about a compromise? I left out the "property of their developers whose names are too numerous to list here" part. I left in the info links and the ref to LICENSE file. Proposed header says:

```
# This file is part of RetroPie-Extra, a supplement to RetroPie.
# For more information, please visit:
#
# https://github.com/RetroPie/RetroPie-Setup
# https://github.com/Exarkuniv/RetroPie-Extra
#
# See the LICENSE file distributed with this source and at
# https://github.com/Exarkuniv/RetroPie-Extra/blob/master/LICENSE
#
```

https://github.com/Exarkuniv/RetroPie-Extra/pull/70
