### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [Exarkuniv/RetroPie-Extra#68]
When retropie_packages.sh is run (either explicitly or via retropie_setup.sh), it loads all of the functions from all of the modules in the RetroPie-Setup directory. On my Pi4, it takes roughly twice as long to launch RP-Setup with the RP-Extra scripts installed (about six seconds), than without them (~3sec).

This is still just a very early-stage idea, but I would eventually like to develop (or see someone else develop, if this inspires anyone who's better at this stuff than I am) a GUI-driven install script that would allow the user to select which of the RetroPie-Extra modules they wish to use, and then copy only those modules into the **ext** folder so operation is not slowed down by the unnecessary functions. There are a lot of modules in RP-Extra and I imagine most people only actually use a handful of them. It would of course have a simple one-click option for "select all" and "select none" and then the user could manually select or de-select individual modules before installing their choices.

**Comment by Exarkuniv** [comment]
I like that idea. 

Maybe have the ports broken up my type

3d shooter
Rpg
Rts, etc

I know I have a few office programs in there also so they can be their own also

I'm in the same boat not sure how to go about doing that. 

But maybe someone out there has something that we can change to make it work.

But this is a idea I'm really down with
